[package]
name = "oxideav-id3"
version = "0.0.4"
edition = "2021"
rust-version = "1.80"
license = "MIT"
repository = "https://github.com/OxideAV/oxideav-id3"
authors = ["Mark Karpeles"]
description = "Pure-Rust ID3v1 / ID3v2 (2.2 / 2.3 / 2.4) tag parser for oxideav"

readme = "README.md"
homepage = "https://github.com/OxideAV/oxideav-id3"
keywords = ["multimedia", "audio", "id3", "mp3", "metadata"]
categories = ["multimedia::audio", "parser-implementations"]

[dependencies]
oxideav-core = "0.0"
